spring:
  profiles:
    active: dev
server:
  port: 1234
#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/lovecampus
#    username: lovecampus
#    password: rootttt
#    driver-class-name: com.mysql.jdbc.Driver

# 发件人（必须正确，否则发送失败），“小
# 密码（注意，某些邮箱需要为SMTP服务单独设置密码，详情查看相关帮助）


# 邮件服务器的SMTP地址，可选，默认为smtp.<发件人邮箱后缀>


